name: Pic
on:
  schedule:
    - cron: 13 */15 * * *
  watch:
    types: started      
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v1

    - name: '修改'
      run: |
        wget -c 'https://acg.yanwz.cn/wallpaper/api.php?134' -O ./images/`date +%Y`/`date +%m`/`date +%Y%m%d%M%N`.jpg --content-on-error --no-check-certificate
        sleep 1s
        wget -c 'https://acg.yanwz.cn/scenery/api.php?134' -O ./images/`date +%Y`/`date +%m`/`date +%Y%m%d%M%N`.jpg --content-on-error --no-check-certificate
        sleep 1s
        wget -c 'https://acg.yanwz.cn/api.php?134' -O ./images/`date +%Y`/`date +%m`/`date +%Y%m%d%M%N`.jpg --content-on-error --no-check-certificate
        echo `date` >> date.txt

      # 部署到 Deploy main branch 
    - name: Deploy main branch 
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: .
        keep_files: true
        publish_branch: pic
        #destination_dir: test
        enable_jekyll: false
        exclude_assets: ''
        
